# Generated by Django 4.2.7 on 2023-11-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='logins', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='login',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='logins', to='auth.permission'),
        ),
    ]
