# Generated by Django 4.2.7 on 2023-11-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_login_colaborador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='colaborador_id',
            field=models.IntegerField(default=7),
        ),
    ]
