# Generated by Django 4.2.3 on 2023-11-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_modulos_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='telefono2',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
