# Generated by Django 4.2.7 on 2023-11-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_empresas_telefono2'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
    ]
