# Generated by Django 4.2.7 on 2023-11-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_modulos_isopen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulos',
            name='isOpen',
        ),
    ]
