# Generated by Django 4.2.7 on 2023-11-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_modulos_isopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='colaborador_id',
            field=models.IntegerField(),
        ),
    ]
