# Generated by Django 4.2.7 on 2023-11-07 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_login_colaborador_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='departamento',
        ),
    ]
