# Generated by Django 4.2.7 on 2023-11-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_colaboradores_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='id_tipoDocumento',
            new_name='id_tipodocumento',
        ),
    ]
