# Generated by Django 4.2.7 on 2023-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_id_tipodocumento_tipodocumento_id_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='empresa_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='rol_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='tipo_documento_id',
            field=models.IntegerField(),
        ),
    ]
