# Generated by Django 4.2.7 on 2023-11-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_colaboradores_empresa_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='contrato_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='empresa_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='num_documento',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='rol_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='telefono',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='tipo_documento_id',
            field=models.CharField(),
        ),
    ]
