# Generated by Django 4.2.7 on 2023-11-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_colaboradores_contrato_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='rol_id',
            field=models.CharField(),
        ),
    ]
