# Generated by Django 4.2.7 on 2023-11-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_colaboradores_rol_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='ciudad',
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='contrato_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='num_documento',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='rol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.roles'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='tipo_documento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipodocumento'),
        ),
    ]
