# Generated by Django 4.2.7 on 2023-11-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_colaboradores_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
