# Generated by Django 4.2.7 on 2023-11-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_colaboradores_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
    ]
