# Generated by Django 4.2.7 on 2023-11-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_colaboradores_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='colaborador_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores'),
        ),
    ]
