# Generated by Django 4.2.7 on 2023-11-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_login_colaborador_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='colaborador_id',
            new_name='documento_num',
        ),
    ]
