# Generated by Django 4.2.7 on 2023-11-10 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_colaborador_id_login_documento_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='documento_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores'),
        ),
    ]
