# Generated by Django 4.2.7 on 2023-11-11 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_colaboradores_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id_login',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='telefono1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='telefono2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='documento_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_login', serialize=False, to='myapp.colaboradores'),
        ),
    ]
