# Generated by Django 4.2.7 on 2023-11-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_imagenusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('vencido', models.BooleanField(default=False)),
                ('documento_num', models.IntegerField()),
            ],
        ),
    ]
