# Generated by Django 4.2.7 on 2023-11-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_token_documento_num_token_documento_num_cryp'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='documento_num',
            field=models.IntegerField(default=23, max_length=15),
            preserve_default=False,
        ),
    ]
