# Generated by Django 4.2.7 on 2023-11-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_token_documento_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='documento_num',
            field=models.IntegerField(),
        ),
    ]
