# Generated by Django 4.2.7 on 2023-11-24 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_token_documento_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_cargo', models.CharField(max_length=99, unique=True)),
                ('estado_cargo', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas')),
            ],
        ),
        migrations.DeleteModel(
            name='Contratos',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='contrato_id',
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='cargo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
