# Generated by Django 4.2.7 on 2023-11-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_cargos_delete_contratos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='cargo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cargos'),
        ),
    ]
